// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKIb3Cy4MuzQuSp6sPdNSaW1hi-fIlp54',
    appId: '1:495566010793:android:09b4dc7c75d2ed42f5acb8',
    messagingSenderId: '495566010793',
    projectId: 'zunda-a0d09',
    storageBucket: 'zunda-a0d09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4XIiwqs-JUHvyOONCKxrcNU6t8QoeBz4',
    appId: '1:495566010793:ios:34c6e0443cc7b8ddf5acb8',
    messagingSenderId: '495566010793',
    projectId: 'zunda-a0d09',
    storageBucket: 'zunda-a0d09.appspot.com',
    iosClientId: '495566010793-7mct9he6h3qhqqborbns8mnc7j9m3597.apps.googleusercontent.com',
    iosBundleId: 'com.zunada.zunada',
  );
}
